"use client";
import { ThemeProvider, createTheme } from "@mui/material/styles";
// import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CssBaseline from "@mui/material/CssBaseline";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

const darkTheme = createTheme({
    palette: {
        mode: "light",
    },
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <ThemeProvider theme={darkTheme}>
                <body className={inter.className}>
                    <CssBaseline />
                    {children}
                </body>
            </ThemeProvider>
        </html>
    );
}
