'use client';
import { ThemeProvider, createTheme } from '@mui/material/styles';
// import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import CssBaseline from '@mui/material/CssBaseline';
import { AppBar, Box, Button, PaletteMode, Toolbar } from '@mui/material';
import Navigation from './components/Navigation';
import { blue } from '@mui/material/colors';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };
//
const mode: PaletteMode = 'light';

// const theme = createTheme({
//     palette: {
//         mode: mode,
//     },
// });

const theme = createTheme({
    palette: {
        mode: mode,
        ...(mode === ('dark' as PaletteMode)
            ? {
                  background: {
                      default: '#000',
                  },
                  // primary: {
                  //     light: '#000',
                  //     main: '#fff',
                  //     dark: '#fff',
                  // },
                  secondary: {
                      main: '#fff',
                      light: '#fff',
                  },
              }
            : {
                  background: {
                      default: '#f2f1ee',
                  },
                  // primary: {
                  //     light: '#000',
                  //     main: '#cecece',
                  //     dark: '#000',
                  // },
                  secondary: {
                      main: '#fff',
                      light: '#fff',
                  },
              }),
    },
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <ThemeProvider theme={theme}>
                <body className={inter.className}>
                    <CssBaseline />
                    <Navigation />
                    {children}
                </body>
            </ThemeProvider>
        </html>
    );
}
